param ([switch]$Run, [string]$Arguments, [switch]$Sign, [string]$Thumbprint)

# ==============================================================================
# PROJECT RONIN // SHOGUN BUILD SYSTEM v7.3.1
# ==============================================================================

# --- 0. SETUP & PATHS ---
$BaseDir = $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($BaseDir)) { $BaseDir = $PWD.Path }
$OutPath = Join-Path $BaseDir "Ronin.ps1"

# Forcefully remove any existing output file (handles locked/read-only states)
if (Test-Path $OutPath) {
    try {
        # Remove read-only attribute if set, then delete
        Set-ItemProperty -Path $OutPath -Name IsReadOnly -Value $false -ErrorAction SilentlyContinue
        Remove-Item $OutPath -Force -ErrorAction Stop
    } catch {
        Write-Warning "[!] Could not remove existing Ronin.ps1: $($_.Exception.Message)"
        Write-Warning "[!] Close any apps that may have the file open and try again."
        exit 1
    }
}

Write-Host "[*] Loading source files..." -ForegroundColor Cyan
Write-Progress -Activity "Project Ronin: Shogun Build" -Status "Loading Source Files..." -PercentComplete 10

# --- 1. READ SOURCE FILES ---
$SrcDir  = Join-Path $BaseDir "src"
$UIDir   = Join-Path $BaseDir "UI"

$CorePath = Join-Path $SrcDir "RoninCore.ps1"
$DBPath   = Join-Path $SrcDir "RoninDB.ps1"
$MainPath = Join-Path $SrcDir "Ronin.ps1"
$XamlPath = Join-Path $UIDir  "Ronin.xaml"

# Validate all source files exist before proceeding
$missing = @()
foreach ($p in @($CorePath, $DBPath, $MainPath, $XamlPath)) {
    if (-not (Test-Path $p)) { $missing += $p }
}
if ($missing.Count -gt 0) {
    Write-Error "[!] BUILD FAILED - Missing source files:`n$($missing -join "`n")"
    exit 1
}

# Read using .NET for consistent UTF-8 handling (no PS 5.1 BOM quirks)
$enc  = [System.Text.Encoding]::UTF8
$Core = [System.IO.File]::ReadAllText($CorePath, $enc)
$DB   = [System.IO.File]::ReadAllText($DBPath,   $enc)
$Main = [System.IO.File]::ReadAllText($MainPath,  $enc)
$Xaml = [System.IO.File]::ReadAllText($XamlPath,  $enc)

# Normalize ALL content to LF line endings. The XAML inlining below uses a literal
# multi-line String.Replace, which is line-ending sensitive: if any source file is
# saved as CRLF while another is LF, the match silently fails and XAML never inlines
# (producing a broken ~170 KB monolith instead of ~261 KB). Normalizing here makes the
# build EOL-agnostic regardless of how each file was saved.
$Core = $Core -replace "`r`n", "`n"
$DB   = $DB   -replace "`r`n", "`n"
$Main = $Main -replace "`r`n", "`n"
$Xaml = $Xaml -replace "`r`n", "`n"

# Strip any BOM from XAML content that would break the here-string injection
$Xaml = $Xaml.TrimStart([char]0xFEFF, [char]0xFFFD, [char]0x200B).Trim()

Write-Progress -Activity "Project Ronin: Shogun Build" -Status "Assembling Monolith..." -PercentComplete 40

# --- 2. INJECT XAML AS HERE-STRING ---
# Replace the entire try/catch XAML loading block with a here-string literal.
# The TrimStart and x:Name->Name replacement that follow still execute at runtime.
$XamlLoadBlock = @'
    # Use .NET ReadAllText for bulletproof UTF-8 handling (auto-detects BOM, no PS quirks)
    try {
        $xamlContent = [System.IO.File]::ReadAllText($XamlPath, [System.Text.Encoding]::UTF8)
    } catch {
        $xamlContent = Get-Content $XamlPath -Raw -Encoding UTF8
    }
'@
# Normalize the needle to LF too, so a CRLF-saved BuildRonin.ps1 still matches $Main.
$XamlLoadBlock = $XamlLoadBlock -replace "`r`n", "`n"

$XamlInlined = "    # MONOLITH: XAML inlined by BuildRonin.ps1`n    `$xamlContent = @'`n$Xaml`n'@"

# Fail loudly if the loader block can't be found (controller diverged from template).
if (-not $Main.Contains($XamlLoadBlock)) {
    Write-Error "[!] BUILD FAILED - Could not locate the XAML loader block in src\Ronin.ps1. The controller may have diverged from the expected template; XAML cannot be inlined."
    exit 1
}
$Main = $Main.Replace($XamlLoadBlock, $XamlInlined)

# --- 3. BYPASS FILE INTEGRITY CHECKS ---
# Monolith has no external files - patch checks to always pass
$Main = $Main.Replace('if ($Missing.Count -gt 0) {', 'if ($false) {')
$Main = $Main.Replace('if ((Test-Path $CorePath) -and (Test-Path $DBPath)) {', 'if ($true) {')

# --- 4. INJECT CORE & DB ---
$Main = $Main.Replace('. $CorePath', $Core)
$Main = $Main.Replace('. $DBPath',   $DB)

Write-Progress -Activity "Project Ronin: Shogun Build" -Status "Saving Monolith..." -PercentComplete 80

# --- 5. ASSEMBLE FINAL SCRIPT ---
$Header = @"
# ==============================================================================
# PROJECT RONIN // SHOGUN EDITION v7.3.1 (DEFINITIVE MONOLITH)
# Built: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
# DO NOT EDIT THIS FILE DIRECTLY - edit files in src\ and UI\ then rebuild
# ==============================================================================
"@

$FinalScript = "$Header`n$Main"

# --- 6. WRITE OUTPUT ---
try {
    # Write as UTF-8 without BOM (standard for PowerShell 5.1 compatibility)
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($OutPath, $FinalScript, $utf8NoBom)
} catch {
    # Fallback: try Set-Content if WriteAllText fails (e.g. unusual ACL on Downloads folder)
    try {
        $FinalScript | Set-Content -Path $OutPath -Encoding UTF8 -Force
        Write-Warning "[!] Used Set-Content fallback (BOM may be added by PS 5.1 - test the output)"
    } catch {
        Write-Error "[!] BUILD FAILED - Cannot write output file: $($_.Exception.Message)"
        Write-Error "[!] Try running BuildRonin.ps1 as Administrator, or move the Ronin folder out of Downloads."
        exit 1
    }
}

# --- 6b. POST-BUILD VERIFICATION (catch silent inlining failures) ---
# A "successful" build that didn't actually inline a module produces a file that looks
# fine but is broken at runtime. Verify the output really is a self-contained monolith.
$built = [System.IO.File]::ReadAllText($OutPath, $enc)
$problems = @()
if (-not $built.Contains('<Window xmlns'))                      { $problems += "XAML did not inline (<Window not found)" }
if ($built.Contains('[System.IO.File]::ReadAllText($XamlPath')) { $problems += "XAML loader stub still present (inline failed)" }
if ($built.Contains('. $CorePath'))                             { $problems += "RoninCore did not inline (. `$CorePath remains)" }
if ($built.Contains('. $DBPath'))                               { $problems += "RoninDB did not inline (. `$DBPath remains)" }
if (-not $built.Contains('Project Ronin Tweak Database'))       { $problems += "Tweak database missing from output" }
if ($problems.Count -gt 0) {
    Write-Error "[!] BUILD PRODUCED A BROKEN MONOLITH:`n  - $($problems -join "`n  - ")"
    Remove-Item $OutPath -Force -ErrorAction SilentlyContinue
    exit 1
}

Write-Progress -Activity "Project Ronin: Shogun Build" -Completed

$size = [Math]::Round((Get-Item $OutPath).Length / 1KB, 2)
Write-Host "[+] PLUS ULTRA: Build complete!" -ForegroundColor Cyan
Write-Host "    Output : $OutPath" -ForegroundColor White
Write-Host "    Size   : $size KB" -ForegroundColor White
Write-Host "    Built  : $(Get-Date -Format 'HH:mm:ss')" -ForegroundColor White
Write-Host "    Verify : self-contained monolith OK (XAML + Core + DB inlined)" -ForegroundColor Green

# --- 7. OPTIONAL CODE SIGNING ---
if ($Sign) {
    $signer = Join-Path $BaseDir "Sign-Ronin.ps1"
    if (Test-Path $signer) {
        Write-Host "[*] Signing build artifacts..." -ForegroundColor Cyan
        & $signer -Thumbprint $Thumbprint
    } else {
        Write-Warning "[!] -Sign requested but Sign-Ronin.ps1 was not found next to BuildRonin.ps1."
    }
}

if ($Run) {
    Write-Host "[*] Launching Ronin..." -ForegroundColor Cyan
    & $OutPath $Arguments 
}
